<actions> Clean out pre-installed stuff on macOS
* Mono is not used but provides some (legacy?) files that can interfere
  with CMake and configure
* Clean out all homebrew packages and install only what is needed
* Provide the path to tw-deps/bin when building dependencies so hunspell
  can pick up autopoint provided by gettext

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -186,18 +186,28 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
 
+      # Mono seems to provide some (potentially incompatible) headers that CMake
+      # might pick up on instead of ours
+    - name: Uninstall Mono
+      run: sudo /bin/sh -c "$(curl -fsSL https://github.com/gurza/cli-toolbox/raw/master/dotnet/mono-uninstall.sh)"
+
+    - name: Install clean Homebrew dependencies
+      shell: bash
+      run: |
+        # Uninstall all packages
+        brew remove --force $(brew list --formula)
+        brew remove --cask --force $(brew list)
+        # Update Homebrew
+        brew update > brew_update.log || { echo "::error::Updating homebrew failed"; cat brew_update.log; exit 1; }
+        # Install needed dependencies
+        brew install automake libtool pkg-config
+
     - name: Install Qt
       uses: jurplel/install-qt-action@v3
       with:
         version: ${{ matrix.qtVersion }}
         modules: ${{ matrix.qtModules }}
 
-    - name: Install Homebrew dependencies
-      shell: bash
-      run: |
-        brew update > brew_update.log || { echo "::error::Updating homebrew failed"; cat brew_update.log; exit 1; }
-        brew uninstall --ignore-dependencies --force brotli cairo fontconfig freetype harfbuzz libjpeg libpng libtiff little-cms2 openjpeg webp zstd
-        brew install automake libtool pkg-config
 
     - name: Cache dependencies
       id: cache-dependencies
@@ -210,8 +220,8 @@ jobs:
       if: steps.cache-dependencies.outputs.cache-hit != 'true'
       shell: bash
       run: |
-        cmake -S ".github/actions/setup-macos" -B ".github/actions/setup-macos/build" -DCMAKE_INSTALL_PREFIX=${RUNNER_TEMP}/tw-deps -DQT_DEFAULT_MAJOR_VERSION=${{ matrix.qtVersionMajor }}
-        PKG_CONFIG_PATH=${RUNNER_TEMP}/tw-deps/lib/pkgconfig cmake --build ".github/actions/setup-macos/build" -v
+        cmake -S ".github/actions/setup-macos" -B ".github/actions/setup-macos/build" -DCMAKE_INSTALL_PREFIX="${RUNNER_TEMP}/tw-deps" -DQT_DEFAULT_MAJOR_VERSION=${{ matrix.qtVersionMajor }}
+        PATH="${RUNNER_TEMP}/tw-deps/bin:$PATH" PKG_CONFIG_PATH=${RUNNER_TEMP}/tw-deps/lib/pkgconfig cmake --build ".github/actions/setup-macos/build" -v
 
     - name: Configure
       run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="${RUNNER_TEMP}/tw-deps" -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE -DQT_DEFAULT_MAJOR_VERSION=${{ matrix.qtVersionMajor }} -DQT_PLUGIN_PATH=${QT_PLUGIN_PATH}
