<actions> Fix macOS package running on 10.14 Mojave (fixes #934)
Homebrew does not allow to set the MACOSX_DEPLOYMENT_TARGET. So instead
of using homebrew, build all dependencies manually. In addition, bundle
the base-14 fonts to work around an issue with poppler to only ever load
font #0, even if multiple fonts are stored in one file (e.g., regular
and bold).

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -108,6 +108,39 @@ jobs:
 
 ################################################################################
 
+  macosx-homebrew:
+    name: Mac OS X (Homebrew)
+    runs-on: macos-latest
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+
+    - name: Install Dependencies
+      run: |
+        # /usr/local/bin/2to3 is symlinked to the native python2 installation
+        # but prevents the homebrew install from succeeding
+        rm -f /usr/local/bin/2to3
+        brew update > brew_update.log || { echo "::error::Updating homebrew failed"; cat brew_update.log; exit 1; }
+        brew install hunspell poppler lua qt5
+
+    - name: Configure
+      run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5"
+
+    - name: Build
+      run: make -j
+      working-directory: build
+
+    - name: Test
+      run: QT_QPA_PLATFORM_PLUGIN_PATH="${Qt5_DIR}/plugins/platforms" ctest -V
+      working-directory: build
+
+    - name: Package
+      id: package
+      uses: ./.github/actions/package-macos
+
+################################################################################
+
   build-macosx-macports:
     name: Mac OS X (MacPorts)
     runs-on: macos-latest
